const dataSliderNexa = [
    {
        id: 1,
        judul: "Solo Leveling Season 2",
        tipe: "Anime",
        status: "Ongoing",
        rating: "9.8",
        totalEpisode: "24 Eps",
        jadwal: "Minggu",
        genre: "Action, Fantasy",
        sinopsis: "Kelanjutan kisah Sung Jin-Woo sebagai Hunter terkuat umat manusia menghadapi ancaman para Monarch.",
        gambar: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&q=80",
        link: "detail-solo-leveling.html"
    },
    {
        id: 2,
        judul: "The Peak of Martial Arts",
        tipe: "Donghua",
        status: "Ongoing",
        rating: "9.5",
        totalEpisode: "400+ Eps",
        jadwal: "Kamis",
        genre: "Cultivation, Martial Arts",
        sinopsis: "Perjalanan melelahkan menuju puncak ilmu bela diri demi melindungi dunia dari kehancuran absolut.",
        gambar: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&q=80",
        link: "detail-martial-peak.html"
    },
    {
        id: 3,
        judul: "Demon Slayer: Infinity Castle",
        tipe: "Anime",
        status: "Ongoing",
        rating: "9.9",
        totalEpisode: "3 Part",
        jadwal: "Sabtu",
        genre: "Action, Shounen",
        sinopsis: "Pertempuran hidup dan mati para Hashira melawan Muzan Kibutsuji di dalam kastil tanpa batas.",
        gambar: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&q=80",
        link: "detail-demon-slayer.html"
    },
    {
        id: 4,
        judul: "Perfect World",
        tipe: "Donghua",
        status: "Ongoing",
        rating: "9.6",
        totalEpisode: "180+ Eps",
        jadwal: "Jumat",
        genre: "Action, Fantasy, Historical",
        sinopsis: "Lahir di dunia unik penuh monster, Shi Hao harus berjuang melewati badai klan demi mendominasi langit.",
        gambar: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
        link: "detail-perfect-world.html"
    },
    {
        id: 5,
        judul: "Jujutsu Kaisen Season 3",
        tipe: "Anime",
        status: "Ongoing",
        rating: "9.7",
        totalEpisode: "23 Eps",
        jadwal: "Rabu",
        genre: "Supernatural, Action",
        sinopsis: "Memasuki Culling Game, Yuji Itadori dan kawan-kawan terjebak dalam ritual mematikan buatan Kenjaku.",
        gambar: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=1200&q=80",
        link: "detail-jujutsu-kaisen.html"
    },
    {
        id: 6,
        judul: "Battle Through the Heavens",
        tipe: "Donghua",
        status: "Ongoing",
        rating: "9.7",
        totalEpisode: "100+ Eps",
        jadwal: "Minggu",
        genre: "Martial Arts, Adventure",
        sinopsis: "Xiao Yan membuktikan kekuatannya kepada dunia setelah sempat dianggap sampah yang kehilangan seluruh bakatnya.",
        gambar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80",
        link: "detail-btth.html"
    },
    {
        id: 7,
        judul: "Chainsaw Man Part 2",
        tipe: "Anime",
        status: "Ongoing",
        rating: "9.4",
        totalEpisode: "12 Eps",
        jadwal: "Selasa",
        genre: "Gore, Dark Fantasy",
        sinopsis: "Kehidupan baru Denji sebagai anak sekolahan sekaligus pahlawan bayangan kota diselimuti oleh ancaman iblis baru.",
        gambar: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80",
        link: "detail-chainsaw-man.html"
    },
    {
        id: 8,
        judul: "Soul Land II",
        tipe: "Donghua",
        status: "Ongoing",
        rating: "9.3",
        totalEpisode: "52 Eps",
        jadwal: "Sabtu",
        genre: "Action, Romance, Magic",
        sinopsis: "Satu juta tahun setelah Tang San, sekte Tang runtuh dan generasi baru berbakat muncul untuk membangkitkannya kembali.",
        gambar: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1200&q=80",
        link: "detail-soul-land.html"
    },
    {
        id: 9,
        judul: "Throne of Seal",
        tipe: "Donghua",
        status: "Ongoing",
        rating: "9.5",
        totalEpisode: "100+ Eps",
        jadwal: "Kamis",
        genre: "Action, Fantasy, Sci-Fi",
        sinopsis: "Saat umat manusia berada di ambang kepunahan oleh iblis, seorang ksatria muda bangkit membawa takhta segel suci.",
        gambar: "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=1200&q=80",
        link: "detail-throne-of-seal.html"
    }
];
